pipeline {

    agent any

    environment {
        IMAGE_TAG    = "${BUILD_NUMBER}"
        DOCKER_IMAGE = "rengarajf5/cicd-e2e"
    }

    stages {

        stage('Checkout App Code') {
            steps {
                git credentialsId: 'github-creds',
                    url: 'https://github.com/renga8680/python-devops.git',
                    branch: 'master'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh '''
                echo "Building Docker Image"
                docker build -t ${DOCKER_IMAGE}:${IMAGE_TAG} .
                '''
            }
        }

        stage('Docker Login') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'dockerhub-creds',
                    usernameVariable: 'DOCKER_USER',
                    passwordVariable: 'DOCKER_PASS'
                )]) {
                    sh '''
                    echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
                    '''
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                sh '''
                docker push ${DOCKER_IMAGE}:${IMAGE_TAG}
                '''
            }
        }

        stage('Update K8S Manifest Repo') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'github-creds',
                    usernameVariable: 'GIT_USER',
                    passwordVariable: 'GIT_TOKEN'
                )]) {
                    sh '''
                    rm -rf cicd-demo-manifests-repo
                    git clone https://github.com/renga8680/cicd-demo-manifests-repo.git
                    cd cicd-demo-manifests-repo

                    sed -i "s|image:.*|image: ${DOCKER_IMAGE}:${IMAGE_TAG}|" deploy.yaml

                    git config user.email "jenkins@local"
                    git config user.name "jenkins"

                    git add deploy.yaml
                    git commit -m "Update image tag to ${IMAGE_TAG}"

                    git push https://${GIT_USER}:${GIT_TOKEN}@github.com/renga8680/cicd-demo-manifests-repo.git master
                    '''
                }
            }
        }
    }
}
